name: Deploy Production

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets
        run: |
          echo "SERVER_IP is set? -> ${{ secrets.SERVER_IP }}"
          echo "SSH Key length -> $(echo "${{ secrets.SERVER_SSH_KEY }}" | wc -c)"
        shell: bash

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Vircosa-3
            git fetch --all
            git reset --hard origin/main
            npm install --omit=dev
            pm2 restart all

